# Generated by Django 5.0.2 on 2024-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('documento', models.CharField(max_length=10, unique=True, verbose_name='Documento identidad')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('primer_nombre', models.CharField(max_length=20, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=20, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Apellido')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('imagen', models.ImageField(blank=True, max_length=50, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
