# Generated by Django 5.0.2 on 2024-08-25 01:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_facturacompra_empleado_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.CharField(max_length=10, unique=True, validators=[users.models.validar_documento_identidad], verbose_name='documento identidad'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
