# Generated by Django 5.0.2 on 2024-08-28 05:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_factura', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], default='venta', max_length=10)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de factura')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pedido Producto',
                'verbose_name_plural': 'Pedidos Productos',
                'db_table': 'pedido_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.factura')),
            ],
            options={
                'verbose_name': 'Factura de compra',
                'verbose_name_plural': 'Facturas de compras',
                'db_table': 'factura_compra',
                'ordering': ['id'],
            },
            bases=('sales.factura',),
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.factura')),
            ],
            options={
                'verbose_name': 'Factura venta',
                'verbose_name_plural': 'Facturas de ventas',
                'db_table': 'factura_venta',
                'ordering': ['id'],
            },
            bases=('sales.factura',),
        ),
        migrations.CreateModel(
            name='FacturaCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por unidad')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Facturas de Compra',
                'db_table': 'factura_compra_detalle',
                'ordering': ['id'],
            },
        ),
    ]
