# Generated by Django 5.0.2 on 2024-08-29 02:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_rename_name_materiaprima_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_factura', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], default='venta', max_length=10)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de factura')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto del Pedido',
                'verbose_name_plural': 'Productos del Pedido',
                'db_table': 'pedido_producto',
                'ordering': ['pedido', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.factura')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'db_table': 'factura_compra',
                'ordering': ['id'],
            },
            bases=('sales.factura',),
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.factura')),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
                'db_table': 'factura_venta',
                'ordering': ['id'],
            },
            bases=('sales.factura',),
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.factura')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'factura_detalle',
                'ordering': ['id'],
            },
        ),
    ]
