# Generated by Django 5.0.2 on 2024-08-28 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='sales.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='facturacompradetalle',
            name='factura_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra_detalle', to='sales.facturacompra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='detalles_compra',
            field=models.ManyToManyField(blank=True, related_name='facturas_compra', to='sales.facturacompradetalle'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='sales.pedido'),
        ),
    ]
