# Generated by Django 5.0.2 on 2024-07-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='empleado',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='compras_empleado', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_factura', to='sales.factura'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='compras_proveedor', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='facturaproducto',
            name='calificacion_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.calificacionproducto'),
        ),
        migrations.AddField(
            model_name='facturaproducto',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.factura'),
        ),
        migrations.AddField(
            model_name='facturaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='empleado',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_empleado', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_factura', to='sales.factura'),
        ),
    ]
