# Generated by Django 5.0.2 on 2024-08-25 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_empleado', to=settings.AUTH_USER_MODEL),
        ),
    ]
