# Generated by Django 5.0.2 on 2024-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificaciones_activas',
            field=models.BooleanField(default=False, verbose_name='Notificaciones Activas'),
        ),
    ]
