# Generated by Django 5.0.2 on 2024-08-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacompra',
            name='detalles_compra',
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='factura_compra_detalles',
            field=models.ManyToManyField(blank=True, related_name='facturas', to='sales.facturacompradetalle'),
        ),
        migrations.AlterField(
            model_name='facturacompradetalle',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra_detalle', to='sales.facturacompra'),
        ),
    ]
