# Generated by Django 5.0.2 on 2024-08-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_facturacompra_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturacompra',
            options={},
        ),
        migrations.AlterModelTable(
            name='facturacompra',
            table=None,
        ),
    ]
