# Generated by Django 5.0.2 on 2024-08-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_factura_iva_alter_factura_subtotal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionProducto',
        ),
    ]
