# Generated by Django 5.0.2 on 2024-08-29 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad producida')),
                ('fecha_produccion', models.DateField(verbose_name='Fecha de producción')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'db_table': 'lote_produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción de materia prima')),
                ('fecha_ven', models.DateField(verbose_name='Fecha de vencimiento')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Materia prima',
                'verbose_name_plural': 'Materias primas',
                'db_table': 'materia_prima',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción de producto')),
                ('valor', models.IntegerField(blank=True, verbose_name='Valor')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.IntegerField(verbose_name='Cantidad utilizada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='inventory.loteproducto')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima')),
            ],
            options={
                'verbose_name': 'Materia prima del lote',
                'verbose_name_plural': 'Materias primas del lote',
                'db_table': 'materia_prima_lote',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
    ]
