# Generated by Django 5.0.2 on 2024-09-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntradaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Entrada de Materia Prima',
                'verbose_name_plural': 'Detalles de Entrada de Materia Prima',
                'db_table': 'detalle_entrada_materia_prima',
                'ordering': ['entrada', 'materia_prima'],
            },
        ),
        migrations.CreateModel(
            name='EntradaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrada')),
                ('total_costo', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Total costo')),
            ],
            options={
                'verbose_name': 'Entrada de Materia Prima',
                'verbose_name_plural': 'Entradas de Materia Prima',
                'db_table': 'entrada_materia_prima',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad producida')),
                ('fecha_produccion', models.DateField(verbose_name='Fecha de producción')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'db_table': 'lote_produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción de materia prima')),
                ('fecha_ven', models.DateField(verbose_name='Fecha de vencimiento')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Materia prima',
                'verbose_name_plural': 'Materias primas',
                'db_table': 'materia_prima',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.IntegerField(verbose_name='Cantidad utilizada')),
            ],
            options={
                'verbose_name': 'Materia prima del lote',
                'verbose_name_plural': 'Materias primas del lote',
                'db_table': 'materia_prima_lote',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción de producto')),
                ('precio', models.IntegerField(blank=True, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
