# Generated by Django 5.0.2 on 2024-09-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamateriaprima',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='users.proveedor'),
        ),
        migrations.AddField(
            model_name='detalleentradamateriaprima',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.entradamateriaprima'),
        ),
        migrations.AddField(
            model_name='detalleentradamateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimalote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='inventory.loteproducto'),
        ),
        migrations.AddField(
            model_name='materiaprimalote',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
    ]
