# Generated by Django 5.0.2 on 2024-08-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='name',
            new_name='nombre',
        ),
    ]
