# Generated by Django 5.0.2 on 2024-09-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprimalote',
            old_name='lote',
            new_name='lote_producto',
        ),
    ]
