# Generated by Django 5.0.2 on 2024-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_lote_materiaprimalote_lote_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descontinuado',
            field=models.BooleanField(default=False, verbose_name='Descontinuado'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_ven',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
