# Generated by Django 5.0.2 on 2024-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_producto_descontinuado_alter_materiaprima_fecha_ven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
