# Generated by Django 5.0.2 on 2024-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradamateriaprima',
            name='total_costo',
        ),
        migrations.AddField(
            model_name='entradamateriaprima',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Total'),
        ),
    ]
