# Generated by Django 5.0.2 on 2024-09-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_materiaprima_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='fecha_ven',
        ),
        migrations.AddField(
            model_name='entradamateriaprima',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='entradamateriaprima',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total costo'),
        ),
        migrations.DeleteModel(
            name='DetalleEntradaMateriaPrima',
        ),
    ]
